# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Acceptance Tests
on:
  push:
    branches:
      - 'develop'
      - 'trunk'
      - 'master'
  pull_request:
    branches:
      - '**'
  # Once weekly on Thursdays at 08:00 UTC.
  schedule:
    - cron: '0 8 * * 4'
  workflow_dispatch:

jobs:
  test:
    name: WP ${{ matrix.wp }} / PHP ${{ matrix.php }}
    strategy:
      matrix:
        wp:
          - 'nightly'
          - '6.2'
        php:
          - '8.2'
          - '7.4'
          - '5.6'
      fail-fast: false
    uses: johnbillion/plugin-infrastructure/.github/workflows/reusable-acceptance-tests.yml@trunk
    with:
      wp: ${{ matrix.wp }}
      php: ${{ matrix.php }}
